module.exports = {
    job_categories: [
        { "name": "Accounting and Finance", "code": "ACC" },
        { "name": "Agriculture and Environment", "code": "AGR" },
        { "name": "Arts and Design", "code": "ART" },
        { "name": "Business and Management", "code": "BUS" },
        { "name": "Education and Teaching", "code": "EDU" },
        { "name": "Engineering", "code": "ENG" },
        { "name": "Healthcare and Medicine", "code": "MED" },
        { "name": "Information Technology", "code": "IT" },
        { "name": "Legal", "code": "LGL" },
        { "name": "Media and Communication", "code": "MCM" },
        { "name": "Public Service and Social Work", "code": "PSW" },
        { "name": "Research and Science", "code": "SCI" },
        { "name": "Sales and Marketing", "code": "MKT" },
        { "name": "Sports and Recreation", "code": "SPT" },
        { "name": "Others", "code": "OTH" }
    ],
    jobs: [
        { "name": "Academic librarian", "category_code": "EDU" },
        { "name": "Accountant", "category_code": "ACC" },
        { "name": "Accounting technician", "category_code": "ACC" },
        { "name": "Actuary", "category_code": "BUS" },
        { "name": "Adult nurse", "category_code": "MED" },
        { "name": "Advertising account executive", "category_code": "MCM" },
        { "name": "Advertising account planner", "category_code": "MCM" },
        { "name": "Advertising copywriter", "category_code": "MCM" },
        { "name": "Advice worker", "category_code": "PSW" },
        { "name": "Advocate (Scotland)", "category_code": "PSW" },
        { "name": "Aeronautical engineer", "category_code": "ENG" },
        { "name": "Agricultural consultant", "category_code": "AGR" },
        { "name": "Agricultural manager", "category_code": "AGR" },
        { "name": "Aid worker/humanitarian worker", "category_code": "PSW" },
        { "name": "Air traffic controller", "category_code": "ENG" },
        { "name": "Airline cabin crew", "category_code": "MED" },
        { "name": "Amenity horticulturist", "category_code": "AGR" },
        { "name": "Analytical chemist", "category_code": "SCI" },
        { "name": "Animal nutritionist", "category_code": "AGR" },
        { "name": "Animator", "category_code": "ART" },
        { "name": "Archaeologist", "category_code": "SCI" },
        { "name": "Architect", "category_code": "ART" },
        { "name": "Architectural technologist", "category_code": "ART" },
        { "name": "Archivist", "category_code": "EDU" },
        { "name": "Armed forces officer", "category_code": "PSW" },
        { "name": "Aromatherapist", "category_code": "MED" },
        { "name": "Art therapist", "category_code": "MED" },
        { "name": "Arts administrator", "category_code": "ART" },
        { "name": "Auditor", "category_code": "ACC" },
        { "name": "Automotive engineer", "category_code": "ENG" },
        { "name": "Barrister", "category_code": "LGL" },
        { "name": "Barrister’s clerk", "category_code": "LGL" },
        { "name": "Bilingual secretary", "category_code": "BUS" },
        { "name": "Biomedical engineer", "category_code": "ENG" },
        { "name": "Biomedical scientist", "category_code": "MED" },
        { "name": "Biotechnologist", "category_code": "SCI" },
        { "name": "Brand manager", "category_code": "MCM" },
        { "name": "Broadcasting presenter", "category_code": "MCM" },
        { "name": "Building control officer/surveyor", "category_code": "ENG" },
        { "name": "Building services engineer", "category_code": "ENG" },
        { "name": "Building surveyor", "category_code": "ENG" },
        { "name": "Camera operator", "category_code": "ART" },
        { "name": "Careers adviser (higher education)", "category_code": "EDU" },
        { "name": "Careers adviser", "category_code": "EDU" },
        { "name": "Careers consultant", "category_code": "BUS" },
        { "name": "Cartographer", "category_code": "SCI" },
        { "name": "Catering manager", "category_code": "OTH" },
        { "name": "Charities administrator", "category_code": "PSW" },
        { "name": "Charities fundraiser", "category_code": "PSW" },
        { "name": "Chemical (process) engineer", "category_code": "ENG" },
        { "name": "Child psychotherapist", "category_code": "MED" },
        { "name": "Children's nurse", "category_code": "MED" },
        { "name": "Chiropractor", "category_code": "MED" },
        { "name": "Civil engineer", "category_code": "ENG" },
        { "name": "Civil Service administrator", "category_code": "PSW" },
        { "name": "Clinical biochemist", "category_code": "MED" },
        { "name": "Clinical cytogeneticist", "category_code": "MED" },
        { "name": "Clinical microbiologist", "category_code": "MED" },
        { "name": "Clinical molecular geneticist", "category_code": "MED" },
        { "name": "Clinical research associate", "category_code": "MED" },
        { "name": "Clinical scientist - tissue typing", "category_code": "MED" },
        { "name": "Clothing and textile technologist", "category_code": "ART" },
        { "name": "Colour technologist", "category_code": "ART" },
        { "name": "Commercial horticulturist", "category_code": "AGR" },
        { "name": "Commercial/residential/rural surveyor", "category_code": "ENG" },
        { "name": "Commissioning editor", "category_code": "MCM" },
        { "name": "Commissioning engineer", "category_code": "ENG" },
        { "name": "Commodity broker", "category_code": "BUS" },
        { "name": "Communications engineer", "category_code": "ENG" },
        { "name": "Community arts worker", "category_code": "PSW" },
        { "name": "Community education officer", "category_code": "EDU" },
        { "name": "Community worker", "category_code": "PSW" },
        { "name": "Company secretary", "category_code": "BUS" },
        { "name": "Computer sales support", "category_code": "IT" },
        { "name": "Computer scientist", "category_code": "IT" },
        { "name": "Conference organiser", "category_code": "BUS" },
        { "name": "Consultant", "category_code": "BUS" },
        { "name": "Consumer rights adviser", "category_code": "PSW" },
        { "name": "Control and instrumentation engineer", "category_code": "ENG" },
        { "name": "Corporate banker", "category_code": "BUS" },
        { "name": "Corporate treasurer", "category_code": "BUS" },
        { "name": "Counsellor", "category_code": "MED" },
        { "name": "Courier/tour guide", "category_code": "OTH" },
        { "name": "Court reporter/verbatim reporter", "category_code": "LGL" },
        { "name": "Credit analyst", "category_code": "ACC" },
        { "name": "Crown Prosecution Service lawyer", "category_code": "LGL" },
        { "name": "Crystallographer", "category_code": "SCI" },
        { "name": "Curator", "category_code": "ART" },
        { "name": "Customs officer", "category_code": "PSW" },
        { "name": "Cyber security specialist", "category_code": "IT" },
        { "name": "Dance movement therapist", "category_code": "MED" },
        { "name": "Data analyst", "category_code": "IT" },
        { "name": "Data scientist", "category_code": "IT" },
        { "name": "Data visualisation analyst", "category_code": "IT" },
        { "name": "Database administrator", "category_code": "IT" },
        { "name": "Debt/finance adviser", "category_code": "BUS" },
        { "name": "Dental hygienist", "category_code": "MED" },
        { "name": "Dentist", "category_code": "MED" },
        { "name": "Design engineer", "category_code": "ENG" },
        { "name": "Dietitian", "category_code": "MED" },
        { "name": "Diplomatic service", "category_code": "PSW" },
        { "name": "Doctor (general practitioner, GP)", "category_code": "MED" },
        { "name": "Doctor (hospital)", "category_code": "MED" },
        { "name": "Dramatherapist", "category_code": "MED" },
        { "name": "Economist", "category_code": "BUS" },
        { "name": "Editorial assistant", "category_code": "MCM" },
        { "name": "Education administrator", "category_code": "EDU" },
        { "name": "Electrical engineer", "category_code": "ENG" },
        { "name": "Electronics engineer", "category_code": "ENG" },
        { "name": "Employment advice worker", "category_code": "PSW" },
        { "name": "Energy conservation officer", "category_code": "PSW" },
        { "name": "Engineering geologist", "category_code": "ENG" },
        { "name": "Environmental education officer", "category_code": "PSW" },
        { "name": "Environmental health officer", "category_code": "PSW" },
        { "name": "Environmental manager", "category_code": "PSW" },
        { "name": "Environmental scientist", "category_code": "SCI" },
        { "name": "Equal opportunities officer", "category_code": "PSW" },
        { "name": "Equality and diversity officer", "category_code": "PSW" },
        { "name": "Ergonomist", "category_code": "OTH" },
        { "name": "Estate agent", "category_code": "OTH" },
        { "name": "European Commission administrators", "category_code": "PSW" },
        { "name": "Exhibition display designer", "category_code": "ART" },
        { "name": "Exhibition organiser", "category_code": "MCM" },
        { "name": "Exploration geologist", "category_code": "SCI" },
        { "name": "Facilities manager", "category_code": "OTH" },
        { "name": "Field trials officer", "category_code": "AGR" },
        { "name": "Financial manager", "category_code": "BUS" },
        { "name": "Firefighter", "category_code": "PSW" },
        { "name": "Fisheries officer", "category_code": "AGR" },
        { "name": "Fitness centre manager", "category_code": "OTH" },
        { "name": "Food scientist", "category_code": "SCI" },
        { "name": "Food technologist", "category_code": "SCI" },
        { "name": "Forensic scientist", "category_code": "SCI" },
        { "name": "Geneticist", "category_code": "SCI" },
        { "name": "Geographical information systems manager", "category_code": "SCI" },
        { "name": "Geomatics/land surveyor", "category_code": "ENG" },
        { "name": "Government lawyer", "category_code": "LGL" },
        { "name": "Government research officer", "category_code": "PSW" },
        { "name": "Graphic designer", "category_code": "ART" },
        { "name": "Health and safety adviser", "category_code": "OTH" },
        { "name": "Health and safety inspector", "category_code": "OTH" },
        { "name": "Health promotion specialist", "category_code": "MED" },
        { "name": "Health service manager", "category_code": "MED" },
        { "name": "Health visitor", "category_code": "MED" },
        { "name": "Herbalist", "category_code": "MED" },
        { "name": "Heritage manager", "category_code": "PSW" },
        { "name": "Higher education administrator", "category_code": "EDU" },
        { "name": "Higher education advice worker", "category_code": "EDU" },
        { "name": "Homeless worker", "category_code": "PSW" },
        { "name": "Horticultural consultant", "category_code": "AGR" },
        { "name": "Hotel manager", "category_code": "OTH" },
        { "name": "Housing adviser", "category_code": "PSW" },
        { "name": "Human resources officer", "category_code": "BUS" },
        { "name": "Hydrologist", "category_code": "SCI" },
        { "name": "Illustrator", "category_code": "ART" },
        { "name": "Immigration officer", "category_code": "PSW" },
        { "name": "Immunologist", "category_code": "MED" },
        { "name": "Industrial/product designer", "category_code": "ART" },
        { "name": "Information scientist", "category_code": "IT" },
        { "name": "Information systems manager", "category_code": "IT" },
        { "name": "Information technology/software trainers", "category_code": "IT" },
        { "name": "Insurance broker", "category_code": "BUS" },
        { "name": "Insurance claims inspector", "category_code": "BUS" },
        { "name": "Insurance risk surveyor", "category_code": "BUS" },
        { "name": "Insurance underwriter", "category_code": "BUS" },
        { "name": "Interpreter", "category_code": "OTH" },
        { "name": "Investment analyst", "category_code": "BUS" },
        { "name": "Investment banker - corporate finance", "category_code": "BUS" },
        { "name": "Investment banker – operations", "category_code": "BUS" },
        { "name": "Investment fund manager", "category_code": "BUS" },
        { "name": "IT consultant", "category_code": "IT" },
        { "name": "IT support analyst", "category_code": "IT" },
        { "name": "Journalist", "category_code": "MCM" },
        { "name": "Laboratory technician", "category_code": "SCI" },
        { "name": "Land-based engineer", "category_code": "ENG" },
        { "name": "Landscape architect", "category_code": "ART" },
        { "name": "Learning disability nurse", "category_code": "MED" },
        { "name": "Learning mentor", "category_code": "EDU" },
        { "name": "Lecturer (adult education)", "category_code": "EDU" },
        { "name": "Lecturer (further education)", "category_code": "EDU" },
        { "name": "Lecturer (higher education)", "category_code": "EDU" },
        { "name": "Legal executive", "category_code": "LGL" },
        { "name": "Leisure centre manager", "category_code": "OTH" },
        { "name": "Licensed conveyancer", "category_code": "LGL" },
        { "name": "Local government administrator", "category_code": "PSW" },
        { "name": "Local government lawyer", "category_code": "LGL" },
        { "name": "Logistics/distribution manager", "category_code": "OTH" },
        { "name": "Magazine features editor", "category_code": "MCM" },
        { "name": "Magazine journalist", "category_code": "MCM" },
        { "name": "Maintenance engineer", "category_code": "ENG" },
        { "name": "Management accountant", "category_code": "ACC" },
        { "name": "Manufacturing engineer", "category_code": "ENG" },
        { "name": "Manufacturing machine operator", "category_code": "ENG" },
        { "name": "Manufacturing toolmaker", "category_code": "ENG" },
        { "name": "Marine scientist", "category_code": "SCI" },
        { "name": "Market research analyst", "category_code": "BUS" },
        { "name": "Market research executive", "category_code": "BUS" },
        { "name": "Marketing account manager", "category_code": "MCM" },
        { "name": "Marketing assistant", "category_code": "MCM" },
        { "name": "Marketing executive", "category_code": "MCM" },
        { "name": "Marketing manager (social media)", "category_code": "MCM" },
        { "name": "Materials engineer", "category_code": "ENG" },
        { "name": "Materials specialist", "category_code": "ENG" },
        { "name": "Mechanical engineer", "category_code": "ENG" },
        { "name": "Media analyst", "category_code": "MCM" },
        { "name": "Media buyer", "category_code": "MCM" },
        { "name": "Media planner", "category_code": "MCM" },
        { "name": "Medical physicist", "category_code": "MED" },
        { "name": "Medical representative", "category_code": "MED" },
        { "name": "Mental health nurse", "category_code": "MED" },
        { "name": "Metallurgist", "category_code": "ENG" },
        { "name": "Meteorologist", "category_code": "SCI" },
        { "name": "Microbiologist", "category_code": "SCI" },
        { "name": "Midwife", "category_code": "MED" },
        { "name": "Mining engineer", "category_code": "ENG" },
        { "name": "Mobile developer", "category_code": "IT" },
        { "name": "Multimedia programmer", "category_code": "IT" },
        { "name": "Multimedia specialists", "category_code": "IT" },
        { "name": "Museum education officer", "category_code": "ART" },
        { "name": "Museum/gallery exhibition officer", "category_code": "ART" },
        { "name": "Music therapist", "category_code": "MED" },
        { "name": "Nanoscientist", "category_code": "SCI" },
        { "name": "Nature conservation officer", "category_code": "PSW" },
        { "name": "Naval architect", "category_code": "ENG" },
        { "name": "Network administrator", "category_code": "IT" },
        { "name": "Nurse", "category_code": "MED" },
        { "name": "Nutritional therapist", "category_code": "MED" },
        { "name": "Nutritionist", "category_code": "MED" },
        { "name": "Occupational therapist", "category_code": "MED" },
        { "name": "Oceanographer", "category_code": "SCI" },
        { "name": "Office manager", "category_code": "OTH" },
        { "name": "Operational researcher", "category_code": "BUS" },
        { "name": "Orthoptist", "category_code": "MED" },
        { "name": "Outdoor pursuits manager", "category_code": "OTH" },
        { "name": "Packaging technologist", "category_code": "ENG" },
        { "name": "Paediatric nurse", "category_code": "MED" },
        { "name": "Paramedic", "category_code": "MED" },
        { "name": "Patent attorney", "category_code": "LGL" },
        { "name": "Patent examiner", "category_code": "LGL" },
        { "name": "Pension scheme manager", "category_code": "BUS" },
        { "name": "Personal assistant", "category_code": "OTH" },
        { "name": "Petroleum engineer", "category_code": "ENG" },
        { "name": "Pharmacist", "category_code": "MED" },
        { "name": "Pharmacologist", "category_code": "MED" },
        { "name": "Pharmacovigilance officer", "category_code": "MED" },
        { "name": "Photographer", "category_code": "ART" },
        { "name": "Physiotherapist", "category_code": "MED" },
        { "name": "Picture researcher", "category_code": "MCM" },
        { "name": "Planning and development surveyor", "category_code": "ENG" },
        { "name": "Planning technician", "category_code": "ENG" },
        { "name": "Plant breeder", "category_code": "AGR" },
        { "name": "Police officer", "category_code": "PSW" },
        { "name": "Political party agent", "category_code": "PSW" },
        { "name": "Political party research officer", "category_code": "PSW" },
        { "name": "Practice nurse", "category_code": "MED" },
        { "name": "Press photographer", "category_code": "ART" },
        { "name": "Press sub-editor", "category_code": "MCM" },
        { "name": "Prison officer", "category_code": "PSW" },
        { "name": "Private music teacher", "category_code": "EDU" },
        { "name": "Probation officer", "category_code": "PSW" },
        { "name": "Product development scientist", "category_code": "SCI" },
        { "name": "Production manager", "category_code": "OTH" },
        { "name": "Programme researcher", "category_code": "MCM" },
        { "name": "Project manager", "category_code": "BUS" },
        { "name": "Psychologist (clinical)", "category_code": "MED" },
        { "name": "Psychologist (educational)", "category_code": "EDU" },
        { "name": "Psychotherapist", "category_code": "MED" },
        { "name": "Public affairs consultant (lobbyist)", "category_code": "PSW" },
        { "name": "Public affairs consultant (research)", "category_code": "PSW" },
        { "name": "Public house manager", "category_code": "OTH" },
        { "name": "Public librarian", "category_code": "EDU" },
        { "name": "Public relations (PR) officer", "category_code": "MCM" },
        { "name": "QA analyst", "category_code": "IT" },
        { "name": "Quality assurance manager", "category_code": "BUS" },
        { "name": "Quantity surveyor", "category_code": "ENG" },
        { "name": "Records manager", "category_code": "OTH" },
        { "name": "Recruitment consultant", "category_code": "BUS" },
        { "name": "Recycling officer", "category_code": "PSW" },
        { "name": "Regulatory affairs officer", "category_code": "BUS" },
        { "name": "Research chemist", "category_code": "SCI" },
        { "name": "Research scientist", "category_code": "SCI" },
        { "name": "Restaurant manager", "category_code": "OTH" },
        { "name": "Retail banker", "category_code": "BUS" },
        { "name": "Retail buyer", "category_code": "BUS" },
        { "name": "Retail manager", "category_code": "OTH" },
        { "name": "Retail merchandiser", "category_code": "OTH" },
        { "name": "Retail pharmacist", "category_code": "MED" },
        { "name": "Sales executive", "category_code": "BUS" },
        { "name": "Sales manager", "category_code": "BUS" },
        { "name": "Scene of crime officer", "category_code": "PSW" },
        { "name": "Secretary", "category_code": "OTH" },
        { "name": "Seismic interpreter", "category_code": "ENG" },
        { "name": "Site engineer", "category_code": "ENG" },
        { "name": "Site manager", "category_code": "ENG" },
        { "name": "Social researcher", "category_code": "BUS" },
        { "name": "Social worker", "category_code": "PSW" },
        { "name": "Software developer", "category_code": "IT" },
        { "name": "Soil scientist", "category_code": "SCI" },
        { "name": "Solicitor", "category_code": "LGL" },
        { "name": "Speech and language therapist", "category_code": "MED" },
        { "name": "Sports coach", "category_code": "OTH" },
        { "name": "Sports development officer", "category_code": "OTH" },
        { "name": "Sports therapist", "category_code": "MED" },
        { "name": "Statistician", "category_code": "BUS" },
        { "name": "Stockbroker", "category_code": "BUS" },
        { "name": "Structural engineer", "category_code": "ENG" },
        { "name": "Systems analyst", "category_code": "IT" },
        { "name": "Systems developer", "category_code": "IT" },
        { "name": "Tax inspector", "category_code": "BUS" },
        { "name": "Teacher (nursery/early years)", "category_code": "EDU" },
        { "name": "Teacher (primary)", "category_code": "EDU" },
        { "name": "Teacher (secondary)", "category_code": "EDU" },
        { "name": "Teacher (special educational needs)", "category_code": "EDU" },
        { "name": "Teaching/classroom assistant", "category_code": "EDU" },
        { "name": "Technical author", "category_code": "MCM" },
        { "name": "Technical sales engineer", "category_code": "ENG" },
        { "name": "TEFL/TESL teacher", "category_code": "EDU" },
        {"name": "Television production assistant", "category_code": "MCM"},
        {"name": "Test automation developer", "category_code": "IT"},
        {"name": "Tour operator", "category_code": "OTH"},
        {"name": "Tourism officer", "category_code": "OTH"},
        {"name": "Tourist information manager", "category_code": "OTH"},
        {"name": "Town and country planner", "category_code": "PSW"},
        {"name": "Toxicologist", "category_code": "SCI"},
        {"name": "Trade union research officer", "category_code": "PSW"},
        {"name": "Trader", "category_code": "BUS"},
        {"name": "Trading standards officer", "category_code": "PSW"},
        {"name": "Training and development officer", "category_code": "BUS"},
        {"name": "Translator", "category_code": "OTH"},
        {"name": "Transportation planner", "category_code": "ENG"},
        {"name": "Travel agent", "category_code": "OTH"},
        {"name": "TV/film/theatre set designer", "category_code": "ART"},
        {"name": "UX designer", "category_code": "IT"},
        {"name": "Validation engineer", "category_code": "ENG"},
        {"name": "Veterinary nurse", "category_code": "MED"},
        {"name": "Veterinary surgeon", "category_code": "MED"},
        {"name": "Video game designer", "category_code": "IT"},
        {"name": "Video game developer", "category_code": "IT"},
        {"name": "Volunteer work organiser", "category_code": "PSW"},
        {"name": "Warehouse manager", "category_code": "OTH"},
        {"name": "Waste disposal officer", "category_code": "PSW"},
        {"name": "Water conservation officer", "category_code": "PSW"},
        {"name": "Water engineer", "category_code": "ENG"},
        {"name": "Web designer", "category_code": "IT"},
        {"name": "Web developer", "category_code": "IT"},
        {"name": "Welfare rights adviser", "category_code": "PSW"},
        {"name": "Writer", "category_code": "MCM"},
        {"name": "Youth worker", "category_code": "PSW"}
    ]
}